name: Deploy Vite + React to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Deploy to timestamp folder
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "Deploying to folder: $TIMESTAMP"
          aws s3 sync dist s3://$S3_BUCKET/$TIMESTAMP --delete

          # Atualiza a pasta 'latest' apontando para o deploy atual
          aws s3 rm s3://$S3_BUCKET/latest --recursive
          aws s3 cp s3://$S3_BUCKET/$TIMESTAMP s3://$S3_BUCKET/latest --recursive
